export interface Skill {
  name: string;
  level: 'beginner' | 'intermediate' | 'advanced' | 'expert';
  icon: string;
}

export interface SkillCategory {
  name: string;
  icon: string;
  skills: Skill[];
}

export interface SkillsData {
  categories: SkillCategory[];
  /** The CV's "Technical Skills" rows, in print order. */
  cv: Array<{ label: string; skills: string[] }>;
}

export interface ProjectLink {
  view?: string;
  code?: string;
}

export interface CaseStudyProcess {
  title: string;
  desc: string;
  icon: string;
}

export interface CaseStudyResult {
  label: string;
  value: string;
}

export interface CaseStudy {
  problem: string;
  solution: string;
  process: CaseStudyProcess[];
  results: CaseStudyResult[];
  comparison?: {
    before: string;
    after: string;
  };
}

export interface Project {
  name: string;
  desc: string;
  metrics: string[];
  images: string[];
  showInHome: boolean;
  categories: string[];
  tags: string[];
  links: ProjectLink;
  caseStudy?: CaseStudy;
  /** Present = listed on the CV (in projects.json order) with this tech line and these bullets. */
  cv?: {
    tech: string[];
    highlights: string[];
    badge?: string;
  };
}

export interface Experience {
  company: string;
  role: string;
  date: string;
  desc: string;
  alignment: 'left' | 'right';
  showInHome: boolean;
  logo?: string;
  /** CV bullets; the CV falls back to `desc` as a single bullet when absent. */
  highlights?: string[];
  location?: string;
}

/** CV education entries (assets/data/education.json, generated by hq). */
export interface Education {
  institution: string;
  degree: string;
  location?: string;
  start: string;
  end: string;
  details: string[];
}

export interface Achievement {
  name: string;
  desc: string;
  images: string[];
  category: 'award' | 'certificate' | 'publication' | 'project' | 'learning' | 'achievement';
  showInHome: boolean;
}

export interface Publication {
  title: string;
  conference: string;
  date: string;
  desc: string;
  images: string[];
  showInHome: boolean;
  paperLink: string | null;
}

export interface Testimonial {
  name: string;
  role: string;
  company: string;
  quote: string;
  avatar?: string;
}

export interface BlogPost {
  title: string;
  description: string;
  url: string;
  platform: 'devto' | 'medium' | 'hashnode' | 'other';
  date: string;
  tags: string[];
  readTime?: string;
}

export interface Profile {
  name: string;
  firstName: string;
  lastName: string;
  title: string;
  tagline: string;
  bio: string;
  email: string;
  github: string;
  linkedin: string;
  orcid: string;
  scholar: string;
  ieeeXplore: string;
  researchgate: string;
  kaggle: string;
  x: string;
  resume: string;
  location: string;
  currentRole: string;
  currentCompany: string;
  available: boolean;
  stats: Array<{ label: string; value: string }>;
}
